name: EMAIL workflow

on:
  workflow_dispatch

jobs:
  email_sender:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run Python script
      run: python email_sender.py
      working-directory: eMAIL_sENDER  # Change to the appropriate directory
      env:
        emailsenderpassword: ${{ secrets.EMAILSENDERPASSWORD }}
