name: EMAIL workflow

on:
  workflow_dispatch:

jobs:
  email_sender:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Run Python script
      run: python email_sender.py
      working-directory: eMAIL_sENDER/.github/workflows/
      env:
        emailsenderpassword: ${{ secrets.EMAILSENDERPASSWORD }}
